/**
 * One-off generator: turn the fixed die-label strings ("Roll", "!") into static
 * SVG path geometry so they render pixel-identically on every platform instead of
 * via the system font (which differs Windows↔iOS and drifts the centring). See
 * docs/cross-platform-ui.md.
 *
 * Run with:  node tools/gen-glyphs.mjs
 * It rewrites src/ui/glyphs.ts. Re-run only if the strings or reference font change.
 *
 * Reference font: Nunito ExtraBold (OFL), via the @fontsource/nunito dev dep — a
 * friendly rounded sans that pairs with the rounded dice/pawns. We bake only the
 * outline geometry (not the font), at em = 1 with the baseline at y = 0, plus each
 * glyph-run's bounding box so the renderer can centre it exactly by bbox.
 */
import opentype from 'opentype.js'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'
import { writeFileSync, readFileSync } from 'node:fs'

const here = dirname(fileURLToPath(import.meta.url))
const fontPath = resolve(here, '../node_modules/@fontsource/nunito/files/nunito-latin-800-normal.woff')
const outPath = resolve(here, '../src/ui/glyphs.ts')

const font = opentype.parse(readFileSync(fontPath).buffer)

// The fixed strings we draw on the dice (keep in sync with src/ui/strings.ts).
const RUNS = { roll: 'Roll', glyph: '!' }

const D = 4 // decimals — em-space coords are 0..~1, so this is sub-pixel on board
const upm = font.unitsPerEm

// Compose each run glyph-by-glyph at em = 1 (baseline y = 0). We avoid
// font.getPath()/forEachGlyph because this font trips opentype.js's GSUB layout
// engine (an unsupported ccmp substitution); plain advance-width layout is all
// "Roll"/"!" need — no kerning or ligatures matter at this size.
const entries = Object.entries(RUNS).map(([key, text]) => {
  const full = new opentype.Path()
  let x = 0
  for (const ch of text) {
    const glyph = font.charToGlyph(ch)
    full.extend(glyph.getPath(x, 0, 1)) // fontSize 1 ⇒ font units / upm
    x += glyph.advanceWidth / upm
  }
  const bb = full.getBoundingBox()
  return { key, d: full.toPathData(D), bb }
})

const body = entries
  .map(
    ({ key, d, bb }) =>
      `  ${key}: {\n` +
      `    d: '${d}',\n` +
      `    cx: ${((bb.x1 + bb.x2) / 2).toFixed(D)},\n` +
      `    cy: ${((bb.y1 + bb.y2) / 2).toFixed(D)},\n` +
      `  },`,
  )
  .join('\n')

const file = `/**
 * AUTO-GENERATED by tools/gen-glyphs.mjs — do not edit by hand.
 *
 * Baked outline geometry for the die-label strings, so they render identically on
 * every platform (no system-font substitution, no per-font centring drift). Each
 * entry is a single SVG path at em = 1 (baseline y = 0) plus the centre of its
 * bounding box, so DieFace can scale and bbox-centre it exactly. Reference font:
 * Nunito ExtraBold (OFL). Re-run the generator to change the font or strings.
 */
export interface Glyph {
  /** SVG path data, drawn at em = 1 with the baseline at y = 0. */
  readonly d: string
  /** Bounding-box centre (em units) — translate this onto the die centre to centre the ink. */
  readonly cx: number
  readonly cy: number
}

export const GLYPHS: Record<'roll' | 'glyph', Glyph> = {
${body}
}
`

writeFileSync(outPath, file)
console.log(`Wrote ${outPath}`)
for (const { key, bb } of entries) {
  console.log(`  ${key}: bbox [${bb.x1.toFixed(3)}, ${bb.y1.toFixed(3)}] → [${bb.x2.toFixed(3)}, ${bb.y2.toFixed(3)}]`)
}
